# Generated by Django 4.0.6 on 2022-08-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0008_consultas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultas',
            name='tipo',
            field=models.IntegerField(default=0),
        ),
    ]
