# Generated by Django 4.0.6 on 2022-08-02 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0009_alter_consultas_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultas',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='twitter.hijos'),
        ),
    ]
