# Generated by Django 4.0.6 on 2022-08-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0011_consultas_nombre_alter_consultas_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultas',
            name='tipo',
            field=models.CharField(default='consulta', max_length=30),
        ),
    ]
