# Generated by Django 3.2.10 on 2022-08-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0014_consultas_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hijos',
            name='campo1_nac',
            field=models.CharField(default='Campo1 Nacimiento', max_length=50),
        ),
        migrations.AddField(
            model_name='hijos',
            name='campo2_nac',
            field=models.CharField(default='Campo2 Nacimiento', max_length=50),
        ),
        migrations.AddField(
            model_name='hijos',
            name='comentarios_nac',
            field=models.CharField(default='Comentarios Nacimiento', max_length=50),
        ),
        migrations.AddField(
            model_name='hijos',
            name='fecha_nac',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hijos',
            name='hora_nac',
            field=models.CharField(default='Hora nacimiento', max_length=50),
        ),
        migrations.AddField(
            model_name='hijos',
            name='lugar_nac',
            field=models.CharField(default='Lugar Nacimiento', max_length=50),
        ),
        migrations.AddField(
            model_name='hijos',
            name='peso_nac',
            field=models.CharField(default='Peso Nacimiento', max_length=50),
        ),
        migrations.AddField(
            model_name='hijos',
            name='talla_nac',
            field=models.CharField(default='Talla Nacimiento', max_length=50),
        ),
        migrations.AddField(
            model_name='hijos',
            name='tipo_nac',
            field=models.CharField(default='Tipo Nacimiento', max_length=50),
        ),
        migrations.AlterField(
            model_name='hijos',
            name='nombre',
            field=models.CharField(default='Nombre', max_length=50),
        ),
        migrations.AlterField(
            model_name='hijos',
            name='sexo',
            field=models.CharField(default='M', max_length=10),
        ),
        migrations.AlterField(
            model_name='hijos',
            name='tipo',
            field=models.CharField(default='Niño', max_length=30),
        ),
    ]
