# Generated by Django 3.2.10 on 2022-08-12 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0015_auto_20220811_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultas',
            name='dato4',
            field=models.CharField(default='dato4', max_length=100),
        ),
        migrations.AddField(
            model_name='consultas',
            name='diam1',
            field=models.CharField(blank=True, default='diam cr', max_length=20),
        ),
        migrations.AddField(
            model_name='consultas',
            name='diam2',
            field=models.CharField(blank=True, default='diam est', max_length=20),
        ),
    ]
