# Generated by Django 3.2.10 on 2022-08-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0016_auto_20220812_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultas',
            name='dato1',
        ),
        migrations.RemoveField(
            model_name='consultas',
            name='dato2',
        ),
        migrations.RemoveField(
            model_name='consultas',
            name='dato3',
        ),
        migrations.RemoveField(
            model_name='consultas',
            name='dato4',
        ),
        migrations.AddField(
            model_name='consultas',
            name='consulta_edad',
            field=models.CharField(default='Edad consulta', max_length=100),
        ),
        migrations.AddField(
            model_name='consultas',
            name='consulta_exta',
            field=models.CharField(default='dato extra', max_length=100),
        ),
        migrations.AddField(
            model_name='consultas',
            name='consulta_fecha',
            field=models.CharField(default='Fecha Consulta', max_length=100),
        ),
        migrations.AddField(
            model_name='consultas',
            name='consulta_proxcita',
            field=models.CharField(default='Prox cita', max_length=100),
        ),
        migrations.AddField(
            model_name='consultas',
            name='consulta_tarea',
            field=models.CharField(default='Tarea', max_length=100),
        ),
        migrations.AlterField(
            model_name='consultas',
            name='tipo',
            field=models.CharField(default='Consulta', max_length=30),
        ),
    ]
